name: Sync LeetCode and Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *" # Runs automatically every 12 hours
  workflow_dispatch: # Gives you the manual run button

permissions:
  contents: write # Grants permission to create the output branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Generate the Snake animation files
      - name: Generate Snake Files
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            
      # Step 2: Extract files and push them to the background output branch
      - name: Push Images to Output Branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
